In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4]
b = [5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
[a[i]+b[i]for i in range(len(a))]

[6, 8, 10, 12]

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [ ]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [ ]:
arr[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [ ]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.eye(3,3).astype(float).dtype

dtype('float64')

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
a=np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.array([1,2,3])
a**2

array([1, 4, 9])

In [ ]:
a*2

array([2, 4, 6])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [ ]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
array=([[1,2,3],
        [4,5,6],
        [7,8,9]])

In [ ]:
a. T

array([[1, 3],
       [2, 4]])

In [ ]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [ ]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,4,5,7])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 7])

In [ ]:
np.reshape(np.reshape(a,(3,4)),(2,6))

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 4, 5, 7]])

In [ ]:
np.reshape(a,(3,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 5, 7]])

In [ ]:
b=np.resize(a,(3,4))

In [ ]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 5, 7]])

In [ ]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([7, 8, 9, 4, 5, 7])]

In [ ]:
arr=np.array([1,2,3,4,5,6])

In [ ]:
b=arr.view()

In [ ]:
b[0]=10

In [ ]:
arr,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [ ]:
c=arr.copy()

In [ ]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [ ]:
c[0]=11

In [ ]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([11,  2,  3,  4,  5,  6]))

In [ ]:
arr=([[1,2,3],
      [4,5,6],
      [7,8,9]])

In [ ]:
a is b

False

In [ ]:
def mean(array):
  n=len(array)
  return np.sum(array)/n

In [ ]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [ ]:
def meadian(array):
  n=len(array)
  return np.sum(array)/n


In [ ]:
meadian(np.array([1,2,3,4,5]))

np.float64(3.0)

In [ ]:
def mode(array):
  n=len(array)
  return np.sum(array)/n

In [ ]:
mode(np.array([1,2,3,4,5]))

np.float64(3.0)

In [ ]:
def variance(array):
  n=len(array)
  m=mean(array)
  return np.sum((array - m)**2)/n

In [ ]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
xmin,xmax=x.min(),x.max()
minmax=(x - xmin)/(xmax - xmin)
print(minmax)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np
x=np.array([0,1,2,3])
1/(1+np.exp(-x))

array([0.5       , 0.73105858, 0.88079708, 0.95257413])

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
np.maximum(0,x)

array([1, 2, 3, 4, 5])